### ISSUE TITLE
Fair comparison

### ISSUE THREAD

**Issue by StarpTech** [icebob/microservices-benchmark#2]
Hi, great to see a benchmark about microservice frameworks in NodeJs. I'm the creator of hemera and would like to tell you my opinion about this test. Hemera is using a message bus called NATS which implicit extra roundtrips.

`Requestor->Server->Responder->Server->Requestor`

This falsified the current benchmark because all `request / response` from Seneca, Moleculer, Nanoservices  are processed in-memory. I propose a test with multiple microservices on different processes or hosts. Even this environment would be wrong to compare because hemera falls under a different category as long as the other frameworks dont use NATS / Broker as transport. If you compare your benchmark of NATS as transport we can get very similiar results.

Thank you

**Comment by icebob** [comment]
Hi @StarpTech! Thanks for you inquiry. Yes it's true. I will create an other test suite where every frameworks will do a "remote" request via a broker/transporter. *I don't know Seneca is supported NATS.*

**Comment by StarpTech** [comment]
@icebob seems so https://github.com/cmfatih/seneca-nats-transport but not official.

**Comment by icebob** [comment]
Thanks. I will try it

**Comment by icebob** [comment]
@StarpTech I created a remote test suite & updated readme with the results.

**Comment by StarpTech** [comment]
@icebob great, thanks for the update.
