### ISSUE TITLE
add nest benchmark

### ISSUE THREAD

**Issue by agalazis** [icebob/microservices-benchmark#5]
No mention for nestjs here ....:
https://nestjs.com/

**Comment by icebob** [comment]
PR is welcome. I don't know nest.

**Comment by danielo515** [comment]
Nest is not a micro-service framework. It does not solves any of the challenges a micro-services architecture has, like service-discovery, inter-service communication, transport, etc.
It does not makes any sense to add such benchmark as it does not makes any sense to have benchmarks with micro.

Regards

**Comment by agalazis** [comment]
Legit point
